import type { MainData } from "./types";

export const seasonalData: MainData[] = [
    {
        during: "立春（2/4頃）",
        word: "東風解凍",
        reading: "はるかぜこおりをとく",
        typing: "harukazekooriwotoku",
    },
    {
        during: "立春（2/4頃）",
        word: "黄鶯睍睆",
        reading: "うぐいすなく",
        typing: "uguisunaku",
    },
    {
        during: "立春（2/4頃）",
        word: "魚上氷",
        reading: "うおこおりをいずる",
        typing: "uokooriwoizuru",
    },
    {
        during: "雨水（2/19頃）",
        word: "土脉潤起",
        reading: "つちのしょううるおいおこる",
        typing: "tutinoshouuruoiokoru",
    },
    {
        during: "雨水（2/19頃）",
        word: "霞始靆",
        reading: "かすみはじめてたなびく",
        typing: "kasumihajimetetanabiku",
    },
    {
        during: "雨水（2/19頃）",
        word: "草木萌動",
        reading: "そうもくめばえいずる",
        typing: "soumokumebaeizuru",
    },
    {
        during: "啓蟄（3/5頃）",
        word: "蟄虫啓戸",
        reading: "すごもりむしとをひらく",
        typing: "sugomorimushitowohiraku",
    },
    {
        during: "啓蟄（3/5頃）",
        word: "桃始笑",
        reading: "ももはじめてわらう",
        typing: "momohajimetewarau",
    },
    {
        during: "啓蟄（3/5頃）",
        word: "菜虫化蝶",
        reading: "なむしちょうとなる",
        typing: "namushichoutonaru",
    },
    {
        during: "春分（3/20頃）",
        word: "雀始巣",
        reading: "すずめはじめてすくう",
        typing: "suzumehajimetesukuu",
    },
    {
        during: "春分（3/20頃）",
        word: "桜始開",
        reading: "さくらはじめてひらく",
        typing: "sakurahajimetehiraku",
    },
    {
        during: "春分（3/20頃）",
        word: "雷乃発声",
        reading: "かみなりすなわちこえをはっす",
        typing: "kaminarisunawatikoewohassu",
    },
    {
        during: "清明（4/4頃）",
        word: "玄鳥至",
        reading: "つばめきたる",
        typing: "tubamekitaru",
    },
    {
        during: "清明（4/4頃）",
        word: "鴻雁北",
        reading: "こうがんきたへかえる",
        typing: "kougankitahekaeru",
    },
    {
        during: "清明（4/4頃）",
        word: "虹始見",
        reading: "にじはじめてあらわる",
        typing: "nijihajimetearawaru",
    },
    {
        during: "穀雨（4/20頃）",
        word: "葭始生",
        reading: "あしはじめてしょうず",
        typing: "ashihajimeteshouzu",
    },
    {
        during: "穀雨（4/20頃）",
        word: "霜止出苗",
        reading: "しもやんでなえいづる",
        typing: "shimoyandenaeizuru",
    },
    {
        during: "穀雨（4/20頃）",
        word: "牡丹華",
        reading: "ぼたんはなさく",
        typing: "botanhanasaku",
    },
    {
        during: "立夏（5/5頃）",
        word: "蛙始鳴",
        reading: "かわずはじめてなく",
        typing: "kawazuhajimetenaku",
    },
    {
        during: "立夏（5/5頃）",
        word: "蚯蚓出",
        reading: "みみずいづる",
        typing: "mimizuizuru",
    },
    {
        during: "立夏（5/5頃）",
        word: "竹笋生",
        reading: "たけのこしょうず",
        typing: "takenokoshouzu",
    },
    {
        during: "小満（5/21頃）",
        word: "蚕起食桑",
        reading: "かいこおきてくわをはむ",
        typing: "kaikookitekuwawohamu",
    },
    {
        during: "小満（5/21頃）",
        word: "紅花栄",
        reading: "べにばなさく",
        typing: "benibanasaku",
    },
    {
        during: "小満（5/21頃）",
        word: "麦秋至",
        reading: "むぎのときいたる",
        typing: "muginotokiitaru",
    },
    {
        during: "芒種（6/5頃）",
        word: "蟷螂生",
        reading: "かまきりしょうず",
        typing: "kamakirishouzu",
    },
    {
        during: "芒種（6/5頃）",
        word: "腐草為螢",
        reading: "くされたるくさほたるとなる",
        typing: "kusaretarukusahotarutonaru",
    },
    {
        during: "芒種（6/5頃）",
        word: "梅子黄",
        reading: "うめのみきばむ",
        typing: "umenomikibamu",
    },
    {
        during: "夏至（6/21頃）",
        word: "乃東枯",
        reading: "なつかれくさかるる",
        typing: "natukarekusakaruru",
    },
    {
        during: "夏至（6/21頃）",
        word: "菖蒲華",
        reading: "あやめはなさく",
        typing: "ayamehanasaku",
    },
    {
        during: "夏至（6/21頃）",
        word: "半夏生",
        reading: "はんげしょうず",
        typing: "hangeshouzu",
    },
    {
        during: "小暑（7/7頃）",
        word: "温風至",
        reading: "あつかぜいたる",
        typing: "atukazeitaru",
    },
    {
        during: "小暑（7/7頃）",
        word: "蓮始開",
        reading: "はすはじめてひらく",
        typing: "hasuhajimetehiraku",
    },
    {
        during: "小暑（7/7頃）",
        word: "鷹乃学習",
        reading: "たかすなわちがくしゅうす",
        typing: "takasunawatigakushuusu",
    },
    {
        during: "大暑（7/22頃）",
        word: "桐始結花",
        reading: "きりはじめてはなをむすぶ",
        typing: "kirihajimetehanaowomusubu",
    },
    {
        during: "大暑（7/22頃）",
        word: "土潤溽暑",
        reading: "つちうるおうてむしあつし",
        typing: "tutiuruoutemushiatushi",
    },
    {
        during: "大暑（7/22頃）",
        word: "大雨時行",
        reading: "たいうときどきにふる",
        typing: "taiutokidokinihuru",
    },
    {
        during: "立秋（8/7頃）",
        word: "涼風至",
        reading: "すずかぜいたる",
        typing: "suzukazeitaru",
    },
    {
        during: "立秋（8/7頃）",
        word: "寒蝉鳴",
        reading: "ひぐらしなく",
        typing: "higurashinaku",
    },
    {
        during: "立秋（8/7頃）",
        word: "蒙霧升降",
        reading: "ふかききりまとう",
        typing: "hukakikirimatou",
    },
    {
        during: "処暑（8/23頃）",
        word: "綿柎開",
        reading: "わたのはなしべひらく",
        typing: "watanohanashibehiraku",
    },
    {
        during: "処暑（8/23頃）",
        word: "天地始粛",
        reading: "てんちはじめてさむし",
        typing: "tentihajimetesamushi",
    },
    {
        during: "処暑（8/23頃）",
        word: "禾乃登",
        reading: "こくものすなわちみのる",
        typing: "kokumonosunawatiminoru",
    },
    {
        during: "白露（9/7頃）",
        word: "草露白",
        reading: "くさのつゆしろし",
        typing: "kusanotuyushiroshi",
    },
    {
        during: "白露（9/7頃）",
        word: "鶺鴒鳴",
        reading: "せきれいなく",
        typing: "sekireinaku",
    },
    {
        during: "白露（9/7頃）",
        word: "玄鳥去",
        reading: "つばめさる",
        typing: "tubamesaru",
    },
    {
        during: "秋分（9/22頃）",
        word: "雷乃収声",
        reading: "かみなりすなわちこえをおさむ",
        typing: "kaminarisunawatikoewoosamu",
    },
    {
        during: "秋分（9/22頃）",
        word: "蟄虫坏戸",
        reading: "むしかくれてとをふさぐ",
        typing: "mushikakuretetowohusagu",
    },
    {
        during: "秋分（9/22頃）",
        word: "水始涸",
        reading: "みずはじめてかる",
        typing: "mizuhajimetekaru",
    },
    {
        during: "寒露（10/8頃）",
        word: "鴻雁来",
        reading: "こうがんきたる",
        typing: "kougankitaru",
    },
    {
        during: "寒露（10/8頃）",
        word: "菊花開",
        reading: "きくのはなひらく",
        typing: "kikunohanahiraku",
    },
    {
        during: "寒露（10/8頃）",
        word: "蟋蟀在戸",
        reading: "きりぎりすとにあり",
        typing: "kirigirisutoniari",
    },
    {
        during: "霜降（10/23頃）",
        word: "霜始降",
        reading: "しもはじめてふる",
        typing: "shimohajimetehuru",
    },
    {
        during: "霜降（10/23頃）",
        word: "霎時施",
        reading: "こさめときどきふる",
        typing: "kosametokidokihuru",
    },
    {
        during: "霜降（10/23頃）",
        word: "楓蔦黄",
        reading: "もみじつたきばむ",
        typing: "momijitutakibamu",
    },
    {
        during: "立冬（11/7頃）",
        word: "山茶始開",
        reading: "つばきはじめてひらく",
        typing: "tubakihajimetehiraku",
    },
    {
        during: "立冬（11/7頃）",
        word: "地始凍",
        reading: "ちはじめてこおる",
        typing: "tihajimetekooru",
    },
    {
        during: "立冬（11/7頃）",
        word: "金盞香",
        reading: "きんせんかさく",
        typing: "kinsenkasaku",
    },
    {
        during: "小雪（11/22頃）",
        word: "虹蔵不見",
        reading: "にじかくれてみえず",
        typing: "nijikakuretemiezu",
    },
    {
        during: "小雪（11/22頃）",
        word: "朔風払葉",
        reading: "きたかぜこのはをはらう",
        typing: "kitakazekonohawoharau",
    },
    {
        during: "小雪（11/22頃）",
        word: "橘始黄",
        reading: "たちばなはじめてきばむ",
        typing: "tatibanahajimetekibamu",
    },
    {
        during: "大雪（12/7頃）",
        word: "閉塞成冬",
        reading: "そらさむくふゆとなる",
        typing: "sorasamukuhuyutonaru",
    },
    {
        during: "大雪（12/7頃）",
        word: "熊蟄穴",
        reading: "くまあなにこもる",
        typing: "kumaananikomoru",
    },
    {
        during: "大雪（12/7頃）",
        word: "鱖魚群",
        reading: "さけのうおむらがる",
        typing: "sakenouomuragaru",
    },
    {
        during: "冬至（12/21頃）",
        word: "乃東生",
        reading: "なつかれくさしょうず",
        typing: "natukarekusashouzu",
    },
    {
        during: "冬至（12/21頃）",
        word: "麋角解",
        reading: "おおしかのつのおつる",
        typing: "ooshikanotunooturu",
    },
    {
        during: "冬至（12/21頃）",
        word: "雪下出麦",
        reading: "ゆきわたりてむぎいづる",
        typing: "yukiwataritemugiizuru",
    },
    {
        during: "小寒（1/5頃）",
        word: "芹乃栄",
        reading: "せりすなわちさかう",
        typing: "serisunawatisakau",
    },
    {
        during: "小寒（1/5頃）",
        word: "水泉動",
        reading: "しみずあたたかをふくむ",
        typing: "shimizuatatakawohukumu",
    },
    {
        during: "小寒（1/5頃）",
        word: "雉始雊",
        reading: "きじはじめてなく",
        typing: "kijihajimetenaku",
    },
    {
        during: "大寒（1/20頃）",
        word: "款冬華",
        reading: "ふきのはなはなさく",
        typing: "hukinohanahanasaku",
    },
    {
        during: "大寒（1/20頃）",
        word: "水沢腹堅",
        reading: "さわみずこおりつめる",
        typing: "sawamizukooritumeru",
    },
    {
        during: "大寒（1/20頃）",
        word: "鶏始乳",
        reading: "にわとりはじめてとやにつく",
        typing: "niwatorihajimetetoyanituku",
    },
];
